### ISSUE TITLE
Dremel and sand 3D prints

### ISSUE THREAD

**Issue by agoich** [FAU2016-ED1Group8/SS-Hardhat#107]

**Comment by fpsoares** [comment]
Look into acetone bath for smooth finish of the print, I tried using a dremmel to sand down pieces and it is very easy to ruin it. Another possibility is just heating it up with a heat gun, also, be careful to not collapse internal structure (also had it happen to me)

**Comment by agoich** [comment]
I'll run it by you first before I do anything
